// <auto-generated />
namespace WebSiteMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identity));
        
        string IMigrationMetadata.Id
        {
            get { return "201510151105437_identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
